<?php

namespace wagesBundle\Repository;

/**
 * acc_usersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class acc_usersRepository extends \Doctrine\ORM\EntityRepository
{
}
