<?php

namespace wagesBundle\Repository;

/**
 * acc_users_groupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class acc_users_groupsRepository extends \Doctrine\ORM\EntityRepository
{
}
