<?php

namespace wagesBundle\Repository;

/**
 * acc_regime_prevoyanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class acc_regime_prevoyanceRepository extends \Doctrine\ORM\EntityRepository
{
}
