<?php

namespace wagesBundle\Repository;

/**
 * acc_retirement_organisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class acc_retirement_organisationRepository extends \Doctrine\ORM\EntityRepository
{
}
