<?php

namespace wagesBundle\Repository;

/**
 * acc_renseignementcomplementaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class acc_renseignementcomplementaireRepository extends \Doctrine\ORM\EntityRepository
{
}
