<?php

namespace wagesBundle\Repository;

/**
 * mutuelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mutuelleRepository extends \Doctrine\ORM\EntityRepository
{
}
